// This code automatically generated by TableCodeGen

using System;
using UnityEngine;
using System.Collections.Generic;
using Cysharp.Threading.Tasks;

public static class ShortStory
{
	public class Row
	{
		public string RECORD_ID;
		public string EN;
		public string JP;
		public string CH;
	}

	static readonly List<Row> rowList = new List<Row>();
	static bool isLoaded = false;
	static Func<SystemLanguage> languageProvider = () => AppSetting.Value.Language;

	public static bool IsLoaded()
	{
		return isLoaded;
	}

	public static List<Row> GetRowList()
	{
		return rowList;
	}

    public static async UniTask LoadLanguageCodes(
        Func<string, UniTask<TextAsset>> load = null,
        Func<SystemLanguage> getLanguage = null)
    {
	    var key = "Config/" + CommonSetting.ShortStoryFile;
	    var csv = await LocalizationTableUtility.LoadCsv(key, load);
	    languageProvider = getLanguage ?? (() => AppSetting.Value.Language);
	    if (csv != null)
        {
            Load(csv);
        }
    }


	static void Load(TextAsset csv)
	{
		LocalizationTableUtility.PopulateRows(
			csv,
			rowList,
			values => new Row
			{
				RECORD_ID = values[0],
				EN = values[1],
				JP = values[2],
				CH = values[3]
			});
		isLoaded = true;
	}

	public static int NumRows()
	{
		return rowList.Count;
	}

	public static Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public static string Get(string languageCode)
	{
		if (String.IsNullOrEmpty(languageCode))
			return null;
		var row = Find_RECORD_ID(languageCode);
		return row == null
			? null
			: LocalizationTableUtility.SelectLanguage(languageProvider(), row.EN, row.JP, row.CH);
	}

	public static Row Find_RECORD_ID(string find)
	{
		return rowList.Find(x => x.RECORD_ID == find);
	}
	public static List<Row> FindAll_RECORD_ID(string find)
	{
		return rowList.FindAll(x => x.RECORD_ID == find);
	}
	public static Row Find_EN(string find)
	{
		return rowList.Find(x => x.EN == find);
	}
	public static List<Row> FindAll_EN(string find)
	{
		return rowList.FindAll(x => x.EN == find);
	}
	public static Row Find_JP(string find)
	{
		return rowList.Find(x => x.JP == find);
	}
	public static List<Row> FindAll_JP(string find)
	{
		return rowList.FindAll(x => x.JP == find);
	}
	public static Row Find_CH(string find)
	{
		return rowList.Find(x => x.CH == find);
	}
	public static List<Row> FindAll_CH(string find)
	{
		return rowList.FindAll(x => x.CH == find);
	}

}
