// This code automatically generated by TableCodeGen
using UnityEngine;
using Soul;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace Log
{
    public class HitBoxLogTable
    {
        static HitBoxLogTable instance;
        public static HitBoxLogTable Instance
        {
            get
            {
                if (instance == null)
                {
                    instance = new HitBoxLogTable();
                }
                return instance;
            }
        }
        
        public void SkillLog(List<Data_Center> members)
        {
            var singleFightLogs = new List<SingleFightLog>();
            for (var i = 0; i < members.Count; i++)
            {
                if (members[i] != null)
                {
                    singleFightLogs.Add(members[i]._MyBehaviorRunner.SingleFightLog);
                }
            }
            
            if (FightGlobalSetting.HitBoxLogger)
            {
                Instance.Load(LoadCurrentToString());
                HitBoxLogger.Instance.LogSummit();
                foreach (var t in singleFightLogs)
                {
                    t.Summary();
                }
                Instance.SaveByCurrentRows_HitBoxLog(Application.persistentDataPath + "/" + CommonSetting.SkillDynamicAnalysis, HitBoxLogger.Instance, singleFightLogs);
                SkillAIDistanceAutoTuner.AutoTune(rowList);
                for (var i = 0; i < singleFightLogs.Count; i++)
                {
                    singleFightLogs[i].Clear();
                }
                HitBoxLogger.Instance.Clear();
            }
        }

        static string LoadCurrentToString()
        {
            var path = Application.persistentDataPath + "/" + CommonSetting.SkillDynamicAnalysis;
            return HitBoxLogger.LoadOrCreateLogFile(path, () =>
            {
                Instance.rowList = new List<Row>();
                for (var i = 0; i < SkillConfigTable.rowList.Count; i++)
                {
                    if (string.IsNullOrEmpty(SkillConfigTable.rowList[i].RECORD_ID))
                    {
                        continue;
                    }

                    Instance.rowList.Add(new Row
                    {
                        RECORD_ID = SkillConfigTable.rowList[i].RECORD_ID,
                        REAL_NAME = SkillConfigTable.rowList[i].REAL_NAME,
                        MONSTER_TYPE = SkillConfigTable.rowList[i].TYPE,
                        Untouched = "0",
                        Touched = "0",
                        Succeeded = "0",
                        TriggeredTimes = "0",
                        InterruptedTimes = "0"
                    });
                }

                Instance.SaveByCurrentRows_HitBoxLog(path, null, null);
            });
        }

        public void ClearRuntimeLogs(List<Data_Center> members)
        {
            if (members != null)
            {
                for (var i = 0; i < members.Count; i++)
                {
                    if (members[i] == null)
                        continue;
                    members[i]._MyBehaviorRunner?.SingleFightLog.Clear();
                }
            }
            HitBoxLogger.Instance.Clear();
        }

        const float LowHitRateThreshold = 0.3f;
        const int LowHitRateMinAttempts = 20;
        const string LowHitRateFlagValue = "LowHitRate";
        const float HighInterruptRatioThreshold = 0.5f;
        const int InterruptMinAttempts = 15;
        const string HighInterruptFlagValue = "HighInterrupt";

        static int ParseInt(string value)
        {
            return int.TryParse(value, out var result) ? result : 0;
        }

        static string FormatHitRateString(int success, int untouched, int touched)
        {
            var attempts = success + untouched + touched;
            if (attempts <= 0)
                return "-";
            var rate = success / (float)attempts * 100f;
            return rate.ToString("0.0");
        }

        static string EvaluateLowHitRateFlag(int success, int untouched, int touched)
        {
            var attempts = success + untouched + touched;
            if (attempts < LowHitRateMinAttempts)
                return string.Empty;
            var rate = attempts > 0 ? success / (float)attempts : 0f;
            return rate < LowHitRateThreshold ? LowHitRateFlagValue : string.Empty;
        }

        static string EvaluateHighInterruptFlag(int interrupted, int triggeredTimes)
        {
            if (triggeredTimes < InterruptMinAttempts)
                return string.Empty;
            var ratio = triggeredTimes > 0 ? interrupted / (float)triggeredTimes : 0f;
            return ratio >= HighInterruptRatioThreshold ? HighInterruptFlagValue : string.Empty;
        }

        static string FormatAverageString(int numerator, int denominator)
        {
            if (denominator <= 0)
                return "-";
            return (numerator / (float)denominator).ToString("0.00");
        }

        static int SumValuesByKeys(IDictionary<string, int> values, params string[] keys)
        {
            if (values == null || keys == null)
                return 0;

            var usedKeys = new HashSet<string>();
            var total = 0;
            for (var i = 0; i < keys.Length; i++)
            {
                var key = keys[i];
                if (string.IsNullOrEmpty(key) || !usedKeys.Add(key))
                    continue;
                if (values.TryGetValue(key, out var value))
                    total += value;
            }
            return total;
        }

        static SkillAIAttrs.Row GetSkillAiRow(Row rowData)
        {
            if (rowData == null || string.IsNullOrEmpty(rowData.RECORD_ID))
                return null;
            return SkillAIAttrs.Find_RECORD_ID(rowData.RECORD_ID);
        }

        public class Row
        {
            public string RECORD_ID;
            public string REAL_NAME;
            public string MONSTER_TYPE;
            public string Untouched;
            public string Touched;
            public string Succeeded;
            public string TriggeredTimes;
            public string InterruptedTimes;
            public string HitRatePercent;
            public string LowHitRateFlag;
            public string HighInterruptFlag;
            public string Attempts;
            public string AvgHitBoxesPerTrigger;
            public string AvgSucceededHitBoxesPerTrigger;
            public string TriggerDisMin;
            public string TriggerDisMax;
            public string TriggerHeight;
        }

        public List<Row> rowList = new List<Row>();
        bool isLoaded = false;

        public bool IsLoaded()
        {
            return isLoaded;
        }
        
        public void Load(TextAsset csv)
        {
            rowList.Clear();
            string[][] grid = CsvParser2.Parse(csv.text);
            for (int i = 1; i < grid.Length; i++)
            {
                    var row = new Row
                    {
                        RECORD_ID = grid[i][0],
                        REAL_NAME = grid[i][1],
                        MONSTER_TYPE = grid[i][2],
                        Untouched = grid[i][3],
                        Touched = grid[i][4],
                        Succeeded = grid[i][5],
                        TriggeredTimes = grid[i][6],
                        InterruptedTimes = grid[i][7],
                        HitRatePercent = grid[i].Length > 8 ? grid[i][8] : string.Empty,
                        LowHitRateFlag = grid[i].Length > 9 ? grid[i][9] : string.Empty,
                        HighInterruptFlag = grid[i].Length > 10 ? grid[i][10] : string.Empty,
                        Attempts = grid[i].Length > 11 ? grid[i][11] : string.Empty,
                        AvgHitBoxesPerTrigger = grid[i].Length > 12 ? grid[i][12] : string.Empty,
                        AvgSucceededHitBoxesPerTrigger = grid[i].Length > 13 ? grid[i][13] : string.Empty,
                        TriggerDisMin = grid[i].Length > 14 ? grid[i][14] : string.Empty,
                        TriggerDisMax = grid[i].Length > 15 ? grid[i][15] : string.Empty,
                        TriggerHeight = grid[i].Length > 16 ? grid[i][16] : string.Empty
                    };
                    rowList.Add(row);
                }
            isLoaded = true;
        }

        void Load(string csv)
        {
            rowList.Clear();
            string[][] grid = CsvParser2.Parse(csv);
            for (int i = 1; i < grid.Length; i++)
            {
                if (grid[i].Length == 0)
                {
                    continue;
                }
                Row row = new Row
                {
                    RECORD_ID = grid[i][0],
                    REAL_NAME = grid[i][1],
                    MONSTER_TYPE = grid[i][2],
                    Untouched = grid[i][3],
                    Touched = grid[i][4],
                    Succeeded = grid[i][5],
                    TriggeredTimes = grid[i][6],
                    InterruptedTimes = grid[i][7],
                    HitRatePercent = grid[i].Length > 8 ? grid[i][8] : string.Empty,
                    LowHitRateFlag = grid[i].Length > 9 ? grid[i][9] : string.Empty,
                    HighInterruptFlag = grid[i].Length > 10 ? grid[i][10] : string.Empty,
                    Attempts = grid[i].Length > 11 ? grid[i][11] : string.Empty,
                    AvgHitBoxesPerTrigger = grid[i].Length > 12 ? grid[i][12] : string.Empty,
                    AvgSucceededHitBoxesPerTrigger = grid[i].Length > 13 ? grid[i][13] : string.Empty,
                    TriggerDisMin = grid[i].Length > 14 ? grid[i][14] : string.Empty,
                    TriggerDisMax = grid[i].Length > 15 ? grid[i][15] : string.Empty,
                    TriggerHeight = grid[i].Length > 16 ? grid[i][16] : string.Empty
                };
                rowList.Add(row);
            }
            isLoaded = true;
        }

        public void SaveByCurrentRows_HitBoxLog(string filePath, HitBoxLogger hitBoxLogger, List<SingleFightLog> singleFightLogs)
        {
            IDictionary<string, int> StateTriggerTimes_whole = new Dictionary<string, int>();
            IDictionary<string, int> StateInterruptedTimes_whole = new Dictionary<string, int>();

            if (singleFightLogs == null)
                goto A;

            for (int index = 0; index < singleFightLogs.Count; index++)
            {
                var stateTriggerTimes = singleFightLogs[index].StateTriggerdTimes;
                var one_interruptedTimes = singleFightLogs[index].StateInterruptedTimes;

                foreach (var keyValuePair in stateTriggerTimes)
                {
                    if (!StateTriggerTimes_whole.ContainsKey(keyValuePair.Key))
                    {
                        StateTriggerTimes_whole.Add(keyValuePair);
                    }
                    else
                    {
                        StateTriggerTimes_whole[keyValuePair.Key] += keyValuePair.Value;
                    }
                }

                foreach (var keyValuePair in one_interruptedTimes)
                {
                    if (!StateInterruptedTimes_whole.ContainsKey(keyValuePair.Key))
                    {
                        StateInterruptedTimes_whole.Add(keyValuePair);
                    }
                    else
                    {
                        StateInterruptedTimes_whole[keyValuePair.Key] += keyValuePair.Value;
                    }
                }
            }
            
            A:
            
            var toDeleteList = new List<Row>();
            foreach (Row row in rowList)
            {
                if (row.REAL_NAME == null)
                    toDeleteList.Add(row);
            }
            foreach (Row row in toDeleteList)
            {
                Debug.Log("由于原先行的一些问题将之予以删除：" + rowList.IndexOf(row));
                rowList.Remove(row);
            }

            string[][] grid = new string[rowList.Count + 1][];
            for (int i = 0; i < grid.Length; i++)
            {
                grid[i] = new string[17];
                if (i == 0)
                {
                    grid[i][0] = "RECORD_ID";
                    grid[i][1] = "REAL_NAME";
                    grid[i][2] = "MONSTER_TYPE";
                    grid[i][3] = "Untouched(未触摸到敌人的hitbox数量)";
                    grid[i][4] = "Touched(触摸到敌人但没造成伤害的hitbox数量)";
                    grid[i][5] = "Successed(成功击中敌人的hitbox数量)";
                    grid[i][6] = "TriggerdTimes(技能使用次数）";
                    grid[i][7] = "InteruptedTimes（技能被打断次数）";
                    grid[i][8] = "HitRate(%)";
                    grid[i][9] = "LowHitRateFlag";
                    grid[i][10] = "HighInterruptFlag";
                    grid[i][11] = "Attempts";
                    grid[i][12] = "AvgHitBoxesPerTrigger";
                    grid[i][13] = "AvgSucceededHitBoxesPerTrigger";
                    grid[i][14] = "TriggerDisMin";
                    grid[i][15] = "TriggerDisMax";
                    grid[i][16] = "TriggerHeight";
                }
                else
                {
                    var rowData = rowList[i - 1];
                    var aiRow = GetSkillAiRow(rowData);
                    if (hitBoxLogger == null)
                    {
                        grid[i][0] = rowData.RECORD_ID;
                        grid[i][1] = rowData.REAL_NAME;
                        grid[i][2] = rowData.MONSTER_TYPE;
                        grid[i][3] = "0";
                        grid[i][4] = "0";
                        grid[i][5] = "0";
                        grid[i][6] = "0";
                        grid[i][7] = "0";
                        grid[i][8] = string.IsNullOrEmpty(rowData.HitRatePercent) ? "-" : rowData.HitRatePercent;
                        grid[i][9] = rowData.LowHitRateFlag ?? string.Empty;
                        grid[i][10] = rowData.HighInterruptFlag ?? string.Empty;
                        grid[i][11] = string.IsNullOrEmpty(rowData.Attempts) ? "0" : rowData.Attempts;
                        grid[i][12] = string.IsNullOrEmpty(rowData.AvgHitBoxesPerTrigger) ? "-" : rowData.AvgHitBoxesPerTrigger;
                        grid[i][13] = string.IsNullOrEmpty(rowData.AvgSucceededHitBoxesPerTrigger) ? "-" : rowData.AvgSucceededHitBoxesPerTrigger;
                        grid[i][14] = string.IsNullOrEmpty(rowData.TriggerDisMin) ? aiRow?.TRIGGER_DIS_MIN ?? string.Empty : rowData.TriggerDisMin;
                        grid[i][15] = string.IsNullOrEmpty(rowData.TriggerDisMax) ? aiRow?.TRIGGER_DIS_MAX ?? string.Empty : rowData.TriggerDisMax;
                        grid[i][16] = string.IsNullOrEmpty(rowData.TriggerHeight) ? aiRow?.TRIGGER_HEIGHT ?? string.Empty : rowData.TriggerHeight;

                    }
                    else
                    {
                        grid[i][0] = rowData.RECORD_ID;
                        grid[i][1] = rowData.REAL_NAME;
                        grid[i][2] = rowData.MONSTER_TYPE;

                        var untouchedVal = SumValuesByKeys(hitBoxLogger.untouchedtimes, rowData.RECORD_ID, rowData.REAL_NAME) + ParseInt(rowData.Untouched);
                        var touchedVal = SumValuesByKeys(hitBoxLogger.touchedtimes, rowData.RECORD_ID, rowData.REAL_NAME) + ParseInt(rowData.Touched);
                        var successVal = SumValuesByKeys(hitBoxLogger.successedtimes, rowData.RECORD_ID, rowData.REAL_NAME) + ParseInt(rowData.Succeeded);
                        var triggerVal = SumValuesByKeys(StateTriggerTimes_whole, rowData.RECORD_ID, rowData.REAL_NAME) + ParseInt(rowData.TriggeredTimes);
                        var interruptedVal = SumValuesByKeys(StateInterruptedTimes_whole, rowData.RECORD_ID, rowData.REAL_NAME) + ParseInt(rowData.InterruptedTimes);
                        var attemptsVal = successVal + untouchedVal + touchedVal;

                        grid[i][3] = untouchedVal.ToString();
                        grid[i][4] = touchedVal.ToString();
                        grid[i][5] = successVal.ToString();
                        grid[i][6] = triggerVal.ToString();
                        grid[i][7] = interruptedVal.ToString();

                        var hitRateString = FormatHitRateString(successVal, untouchedVal, touchedVal);
                        var flag = EvaluateLowHitRateFlag(successVal, untouchedVal, touchedVal);
                        var interruptFlag = EvaluateHighInterruptFlag(interruptedVal, triggerVal);
                        grid[i][8] = hitRateString;
                        grid[i][9] = flag;
                        grid[i][10] = interruptFlag;
                        grid[i][11] = attemptsVal.ToString();
                        grid[i][12] = FormatAverageString(attemptsVal, triggerVal);
                        grid[i][13] = FormatAverageString(successVal, triggerVal);
                        grid[i][14] = aiRow?.TRIGGER_DIS_MIN ?? string.Empty;
                        grid[i][15] = aiRow?.TRIGGER_DIS_MAX ?? string.Empty;
                        grid[i][16] = aiRow?.TRIGGER_HEIGHT ?? string.Empty;

                        rowData.HitRatePercent = hitRateString;
                        rowData.LowHitRateFlag = flag;
                        rowData.HighInterruptFlag = interruptFlag;
                        rowData.Attempts = attemptsVal.ToString();
                        rowData.AvgHitBoxesPerTrigger = grid[i][12];
                        rowData.AvgSucceededHitBoxesPerTrigger = grid[i][13];
                        rowData.TriggerDisMin = grid[i][14];
                        rowData.TriggerDisMax = grid[i][15];
                        rowData.TriggerHeight = grid[i][16];
                    }
                }
            }
            var delimiter = ",";
            var sb = new StringBuilder();
            for (var index = 0; index < grid.Length; index++)
                sb.AppendLine(string.Join(delimiter, grid[index]));
            Debug.Log("尝试最终保存文件" + filePath);
            var outStream = File.CreateText(filePath);
            outStream.WriteLine(sb);
            outStream.Close();
        }
    }
}
