-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgJh/R2ceRu+P1QRCu
i0zuQ6J3vdPC+tD1dTlJ61cOWbygCgYIKoZIzj0DAQehRANCAATqNL61gRP+qKtw
smcBCnk7qoOuCStE+i9WK6kCcfuukbSXPUfkOHRYLunFCwWZXV11vXGAu6CEREs4
2qtsZLIW
-----END PRIVATE KEY-----